Don't crash when a task is explicitly killed.
python-drmaa occasionally raises a naked Exception with the mysterious
words "code 24: no usage information was returned for the completed job".
This can happen when a job is explicitly killed, either by the user or
by the cluster manager, or - maybe? - when there is a timeout or other
glitch in SGE. Unfortunately, drmaa cannot identify which job died.

This patch prevents a crash, catches that specific exception, and adds
some bookkeeping to DRM_DRMAA so that the identity of the dead job can
be (eventually) guessed.

Here's the sort of bad cluster weather that could trigger the bug this
commit is intended to fix.

INFO: 2016-04-29 12:06:27: <Task[25] Reads_To_Alignments_Script(core_req=16, drm='drmaa:ge', in_sample_info='SQ6158_LS72374_XE99780/input/sample.info')> Finished successfully
error: commlib error: got read error (closing "qmaster-3.clvr.locusdev.net/qmaster/1")
commlib returns can't find connection

error: commlib error: got read error (closing "qmaster-3.clvr.locusdev.net/qmaster/1")
error: commlib error: got read error (closing "qmaster-3.clvr.locusdev.net/qmaster/1")
commlib returns can't find connection

Traceback (most recent call last):
  File "/locus/data/dev_analysis/lims-pipe/opt//locus-pipe/mdp-pipe/bin/r2v/process-sequencing-run", line 739, in <module>
    sys.exit(main())
  File "/locus/data/dev_analysis/lims-pipe/opt//locus-pipe/mdp-pipe/bin/r2v/process-sequencing-run", line 214, in main
    cosmos_ok = workflow.run(log_out_dir_func=log_dir_for_task)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/models/Workflow.py", line 380, in run
    _run(self, session, task_queue)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/models/Workflow.py", line 516, in _run
    for task in _process_finished_tasks(workflow.jobmanager):
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/models/Workflow.py", line 571, in _process_finished_tasks
    for task in jobmanager.get_finished_tasks():
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/job/JobManager.py", line 100, in get_finished_tasks
    for task, job_info_dict in self.get_drm(drm).filter_is_done(list(tasks)):
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/job/drm/drm_drmaa.py", line 50, in filter_is_done
    extra_jobinfo = get_drmaa_session().wait(jobId=drmaa.Session.JOB_IDS_SESSION_ANY, timeout=1)._asdict()
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/drmaa/session.py", line 471, in wait
    rusage)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/drmaa/helpers.py", line 299, in c
    return f(*(args + (error_buffer, sizeof(error_buffer))))
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
Exception: code 24: no usage information was returned for the completed job
ERROR: 2016-04-29 15:45:02: Workflow <Workflow[1] _locus_data_dev_analysis_lims-pipe_opt__locus-pipe_mdp-pipe_bin_r2v_process-sequencing-run> has a status of running atexit!
WARNING: 2016-04-29 15:45:02: Terminating <Workflow[1] _locus_data_dev_analysis_lims-pipe_opt__locus-pipe_mdp-pipe_bin_r2v_process-sequencing-run>!
INFO: 2016-04-29 15:45:02: Processing finished tasks and terminating 35 running tasks
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/models/Workflow.py", line 595, in cleanup_check
    workflow.terminate(due_to_failure=True)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/models/Workflow.py", line 406, in terminate
    self.jobmanager.terminate()
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/job/JobManager.py", line 82, in terminate
    self.get_drm(drm).kill_tasks(tasks)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/job/drm/drm_drmaa.py", line 86, in kill_tasks
    self.kill(t)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/cosmos/job/drm/drm_drmaa.py", line 82, in kill
    get_drmaa_session().control(str(task.drm_jobID), drmaa.JobControlAction.TERMINATE)
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/drmaa/session.py", line 381, in control
    c(drmaa_control, jobId, string_to_control_action(operation))
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/drmaa/helpers.py", line 299, in c
    return f(*(args + (error_buffer, sizeof(error_buffer))))
  File "/locus/home/mpearson/sync/locus-pipe/ve/local/lib/python2.7/site-packages/drmaa/errors.py", line 151, in error_check
    raise _ERRORS[code - 1](error_string)
InvalidJobException: code 18: There are no jobs registered